// <auto-generated />
using System;
using AgentHierarchyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentHierarchyApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110060203_AddClientTables")]
    partial class AddClientTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentHierarchyApi.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HierarchyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentAgentId")
                        .HasColumnType("integer");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentCode")
                        .IsUnique();

                    b.HasIndex("HierarchyId");

                    b.HasIndex("ParentAgentId");

                    b.HasIndex("RankId");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentCode = "AE0001",
                            AgentName = "Executive Agent A9",
                            CreatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496),
                            HierarchyId = 9,
                            IsActive = true,
                            RankId = 3,
                            UpdatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496)
                        },
                        new
                        {
                            Id = 2,
                            AgentCode = "AE0002",
                            AgentName = "Executive Agent A8",
                            CreatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496),
                            HierarchyId = 8,
                            IsActive = true,
                            ParentAgentId = 1,
                            RankId = 3,
                            UpdatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496)
                        },
                        new
                        {
                            Id = 3,
                            AgentCode = "AE0003",
                            AgentName = "Executive Agent A7",
                            CreatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496),
                            HierarchyId = 7,
                            IsActive = true,
                            ParentAgentId = 2,
                            RankId = 3,
                            UpdatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496)
                        },
                        new
                        {
                            Id = 4,
                            AgentCode = "AL0001",
                            AgentName = "Leader Agent A6",
                            CreatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496),
                            HierarchyId = 6,
                            IsActive = true,
                            ParentAgentId = 3,
                            RankId = 2,
                            UpdatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496)
                        },
                        new
                        {
                            Id = 5,
                            AgentCode = "AL0002",
                            AgentName = "Leader Agent A5",
                            CreatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496),
                            HierarchyId = 5,
                            IsActive = true,
                            ParentAgentId = 4,
                            RankId = 2,
                            UpdatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496)
                        },
                        new
                        {
                            Id = 6,
                            AgentCode = "AL0003",
                            AgentName = "Leader Agent A4",
                            CreatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496),
                            HierarchyId = 4,
                            IsActive = true,
                            ParentAgentId = 5,
                            RankId = 2,
                            UpdatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496)
                        },
                        new
                        {
                            Id = 7,
                            AgentCode = "AG0001",
                            AgentName = "General Agent A1-1",
                            CreatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496),
                            HierarchyId = 1,
                            IsActive = true,
                            ParentAgentId = 6,
                            RankId = 1,
                            UpdatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496)
                        },
                        new
                        {
                            Id = 8,
                            AgentCode = "AG0002",
                            AgentName = "General Agent A1-2",
                            CreatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496),
                            HierarchyId = 1,
                            IsActive = true,
                            ParentAgentId = 6,
                            RankId = 1,
                            UpdatedDate = new DateTime(2025, 11, 10, 6, 2, 3, 502, DateTimeKind.Utc).AddTicks(6496)
                        });
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLIENT_CODE");

                    b.Property<string>("ClientTypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLIENT_TYPE_CODE");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_DATE");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<byte[]>("EducationLevelCode")
                        .HasColumnType("bytea")
                        .HasColumnName("EDUCATION_LEVEL_CODE");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("FirstNameEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FIRST_NAME_EN");

                    b.Property<string>("GenderCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("GENDER_CODE");

                    b.Property<DateTime?>("IdentityExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("IDENTITY_EXPIRY_DATE");

                    b.Property<byte[]>("IdentityNo")
                        .HasColumnType("bytea")
                        .HasColumnName("IDENTITY_NO");

                    b.Property<bool?>("IdentityPermanent")
                        .HasColumnType("boolean")
                        .HasColumnName("IDENTITY_PERMANENT");

                    b.Property<string>("IdentityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("IDENTITY_TYPE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("LanguagePreferenceCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LANGUAGE_PREFERENCE_CODE");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("LastNameEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LAST_NAME_EN");

                    b.Property<string>("MaritalStatusCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("MARITAL_STATUS_CODE");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("MIDDLE_NAME");

                    b.Property<string>("MiddleNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("MIDDLE_NAME_EN");

                    b.Property<string>("NationalityCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NATIONALITY_CODE");

                    b.Property<string>("OrganizationBusinessType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ORGANIZATION_BUSINESS_TYPE");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ORGANIZATION_NAME");

                    b.Property<string>("OrganizationNameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ORGANIZATION_NAME_EN");

                    b.Property<DateTime?>("OrganizationRegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ORGANIZATION_REGISTRATION_DATE");

                    b.Property<string>("PlaceOfBirthCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PLACE_OF_BIRTH_CITY");

                    b.Property<string>("PlaceOfBirthCountryCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PLACE_OF_BIRTH_COUNTRY_CODE");

                    b.Property<decimal?>("PremiumCapacity")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("PREMIUM_CAPACITY");

                    b.Property<byte[]>("PrimaryIncomeLevelCode")
                        .HasColumnType("bytea")
                        .HasColumnName("PRIMARY_INCOME_LEVEL_CODE");

                    b.Property<byte[]>("PrimaryIncomePerYear")
                        .HasColumnType("bytea")
                        .HasColumnName("PRIMARY_INCOME_PER_YEAR");

                    b.Property<string>("PrimaryOccupationBusinessType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PRIMARY_OCCUPATION_BUSINESS_TYPE");

                    b.Property<byte[]>("PrimaryOccupationCode")
                        .HasColumnType("bytea")
                        .HasColumnName("PRIMARY_OCCUPATION_CODE");

                    b.Property<string>("PrimaryOccupationOrganizationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PRIMARY_OCCUPATION_ORGANIZATION_NAME");

                    b.Property<byte[]>("PrimaryOccupationPositionCode")
                        .HasColumnType("bytea")
                        .HasColumnName("PRIMARY_OCCUPATION_POSITION_CODE");

                    b.Property<string>("ReceivesEmailNews")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("RECEIVES_EMAIL_NEWS");

                    b.Property<string>("RefId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("REF_ID");

                    b.Property<byte[]>("ReligionCode")
                        .HasColumnType("bytea")
                        .HasColumnName("RELIGION_CODE");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("REMARK");

                    b.Property<byte[]>("SecondaryIncomeLevelCode")
                        .HasColumnType("bytea")
                        .HasColumnName("SECONDARY_INCOME_LEVEL_CODE");

                    b.Property<byte[]>("SecondaryIncomePerYear")
                        .HasColumnType("bytea")
                        .HasColumnName("SECONDARY_INCOME_PER_YEAR");

                    b.Property<string>("SecondaryOccupationBusinessType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SECONDARY_OCCUPATION_BUSINESS_TYPE");

                    b.Property<byte[]>("SecondaryOccupationCode")
                        .HasColumnType("bytea")
                        .HasColumnName("SECONDARY_OCCUPATION_CODE");

                    b.Property<string>("SecondaryOccupationOrganizationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SECONDARY_OCCUPATION_ORGANIZATION_NAME");

                    b.Property<byte[]>("SecondaryOccupationPositionCode")
                        .HasColumnType("bytea")
                        .HasColumnName("SECONDARY_OCCUPATION_POSITION_CODE");

                    b.Property<string>("SuffixName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SUFFIX_NAME");

                    b.Property<string>("SuffixNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SUFFIX_NAME_EN");

                    b.Property<byte[]>("TaxId")
                        .HasColumnType("bytea")
                        .HasColumnName("TAX_ID");

                    b.Property<DateTime?>("TerminatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TERMINATED_DATE");

                    b.Property<bool?>("TerminatedFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("TERMINATED_FLAG");

                    b.Property<string>("TerminatedReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TERMINATED_REASON");

                    b.Property<string>("TitleCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TITLE_CODE");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode")
                        .IsUnique();

                    b.HasIndex("RefId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("T_CLIENT", (string)null);
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressAlley")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_ALLEY");

                    b.Property<string>("AddressDetail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ADDRESS_DETAIL");

                    b.Property<string>("AddressMoo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ADDRESS_MOO");

                    b.Property<string>("AddressNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ADDRESS_NO");

                    b.Property<string>("AddressRoad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_ROAD");

                    b.Property<string>("AddressTypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ADDRESS_TYPE_CODE");

                    b.Property<string>("AddressVillageBuilding")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_VILLAGE_BUILDING");

                    b.Property<string>("AddressWorkplaceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_WORKPLACE_NAME");

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLIENT_CODE");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("COUNTRY_CODE");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("DistrictCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DISTRICT_CODE");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_PRIMARY");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("POSTAL_CODE");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PROVINCE_CODE");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("REMARK");

                    b.Property<string>("SubdistrictCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SUBDISTRICT_CODE");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("T_CLIENT_ADDRESS", (string)null);
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLIENT_CODE");

                    b.Property<string>("ContactTypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CONTACT_TYPE_CODE");

                    b.Property<string>("ContactValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("CONTACT_VALUE");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_PRIMARY");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("REMARK");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("T_CLIENT_CONTACT", (string)null);
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLIENT_CODE");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_DATE");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EFFECTIVE_DATE");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EXPIRY_DATE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("PolicyNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("POLICY_NO");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("REFERENCE_NO");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("REMARK");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROLE_CODE");

                    b.Property<int?>("RoleSeqNo")
                        .HasColumnType("integer")
                        .HasColumnName("ROLE_SEQ_NO");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("T_CLIENT_ROLE", (string)null);
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Hierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HierarchyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("HierarchyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyCode")
                        .IsUnique();

                    b.HasIndex("RankId");

                    b.ToTable("Hierarchies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HierarchyCode = "A1",
                            HierarchyName = "Hierarchy A1",
                            Level = 1,
                            RankId = 1
                        },
                        new
                        {
                            Id = 2,
                            HierarchyCode = "A2",
                            HierarchyName = "Hierarchy A2",
                            Level = 2,
                            RankId = 1
                        },
                        new
                        {
                            Id = 3,
                            HierarchyCode = "A3",
                            HierarchyName = "Hierarchy A3",
                            Level = 3,
                            RankId = 1
                        },
                        new
                        {
                            Id = 4,
                            HierarchyCode = "A4",
                            HierarchyName = "Hierarchy A4",
                            Level = 4,
                            RankId = 2
                        },
                        new
                        {
                            Id = 5,
                            HierarchyCode = "A5",
                            HierarchyName = "Hierarchy A5",
                            Level = 5,
                            RankId = 2
                        },
                        new
                        {
                            Id = 6,
                            HierarchyCode = "A6",
                            HierarchyName = "Hierarchy A6",
                            Level = 6,
                            RankId = 2
                        },
                        new
                        {
                            Id = 7,
                            HierarchyCode = "A7",
                            HierarchyName = "Hierarchy A7",
                            Level = 7,
                            RankId = 3
                        },
                        new
                        {
                            Id = 8,
                            HierarchyCode = "A8",
                            HierarchyName = "Hierarchy A8",
                            Level = 8,
                            RankId = 3
                        },
                        new
                        {
                            Id = 9,
                            HierarchyCode = "A9",
                            HierarchyName = "Hierarchy A9",
                            Level = 9,
                            RankId = 3
                        });
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("RankCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RankCode")
                        .IsUnique();

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 1,
                            RankCode = "AG",
                            RankName = "Agent General"
                        },
                        new
                        {
                            Id = 2,
                            Level = 2,
                            RankCode = "AL",
                            RankName = "Agent Leader"
                        },
                        new
                        {
                            Id = 3,
                            Level = 3,
                            RankCode = "AE",
                            RankName = "Agent Executive"
                        });
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Agent", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Hierarchy", "Hierarchy")
                        .WithMany("Agents")
                        .HasForeignKey("HierarchyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentHierarchyApi.Models.Agent", "ParentAgent")
                        .WithMany("ChildAgents")
                        .HasForeignKey("ParentAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgentHierarchyApi.Models.Rank", "Rank")
                        .WithMany("Agents")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hierarchy");

                    b.Navigation("ParentAgent");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Client", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Agent", "ReferenceAgent")
                        .WithMany()
                        .HasForeignKey("RefId")
                        .HasPrincipalKey("AgentCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReferenceAgent");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientAddress", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Client", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientCode")
                        .HasPrincipalKey("ClientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientContact", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Client", "Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientCode")
                        .HasPrincipalKey("ClientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientRole", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Client", "Client")
                        .WithMany("Roles")
                        .HasForeignKey("ClientCode")
                        .HasPrincipalKey("ClientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Hierarchy", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Rank", "Rank")
                        .WithMany("Hierarchies")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.License", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Agent", "Agent")
                        .WithMany("Licenses")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Agent", b =>
                {
                    b.Navigation("ChildAgents");

                    b.Navigation("Licenses");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Hierarchy", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Rank", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Hierarchies");
                });
#pragma warning restore 612, 618
        }
    }
}
