// <auto-generated />
using System;
using AgentHierarchyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgentHierarchyApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251113091038_AddLeaderCodeToAgent")]
    partial class AddLeaderCodeToAgent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgentHierarchyApi.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Agent");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HierarchyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LeaderCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ParentAgentId")
                        .HasColumnType("integer");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentCode")
                        .IsUnique();

                    b.HasIndex("AgentType");

                    b.HasIndex("HierarchyId");

                    b.HasIndex("LeaderCode");

                    b.HasIndex("ParentAgentId");

                    b.HasIndex("RankId");

                    b.ToTable("agents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentCode = "AE0001",
                            AgentName = "Executive Agent A9",
                            AgentType = "Agent",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            HierarchyId = 9,
                            IsActive = true,
                            RankId = 3,
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176)
                        },
                        new
                        {
                            Id = 2,
                            AgentCode = "AE0002",
                            AgentName = "Executive Agent A8",
                            AgentType = "Agent",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            HierarchyId = 8,
                            IsActive = true,
                            ParentAgentId = 1,
                            RankId = 3,
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176)
                        },
                        new
                        {
                            Id = 3,
                            AgentCode = "AE0003",
                            AgentName = "Executive Agent A7",
                            AgentType = "Agent",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            HierarchyId = 7,
                            IsActive = true,
                            ParentAgentId = 2,
                            RankId = 3,
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176)
                        },
                        new
                        {
                            Id = 4,
                            AgentCode = "AL0001",
                            AgentName = "Leader Agent A6",
                            AgentType = "Agent",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            HierarchyId = 6,
                            IsActive = true,
                            ParentAgentId = 3,
                            RankId = 2,
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176)
                        },
                        new
                        {
                            Id = 5,
                            AgentCode = "AL0002",
                            AgentName = "Leader Agent A5",
                            AgentType = "Agent",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            HierarchyId = 5,
                            IsActive = true,
                            ParentAgentId = 4,
                            RankId = 2,
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176)
                        },
                        new
                        {
                            Id = 6,
                            AgentCode = "AL0003",
                            AgentName = "Leader Agent A4",
                            AgentType = "Agent",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            HierarchyId = 4,
                            IsActive = true,
                            ParentAgentId = 5,
                            RankId = 2,
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176)
                        },
                        new
                        {
                            Id = 7,
                            AgentCode = "AG0001",
                            AgentName = "General Agent A1-1",
                            AgentType = "Agent",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            HierarchyId = 1,
                            IsActive = true,
                            ParentAgentId = 6,
                            RankId = 1,
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176)
                        },
                        new
                        {
                            Id = 8,
                            AgentCode = "AG0002",
                            AgentName = "General Agent A1-2",
                            AgentType = "Agent",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            HierarchyId = 1,
                            IsActive = true,
                            ParentAgentId = 6,
                            RankId = 1,
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176)
                        });
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLIENT_CODE");

                    b.Property<string>("ClientTypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLIENT_TYPE_CODE");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_DATE");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<byte[]>("EducationLevelCode")
                        .HasColumnType("bytea")
                        .HasColumnName("EDUCATION_LEVEL_CODE");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("FirstNameEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FIRST_NAME_EN");

                    b.Property<string>("GenderCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("GENDER_CODE");

                    b.Property<DateTime?>("IdentityExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("IDENTITY_EXPIRY_DATE");

                    b.Property<byte[]>("IdentityNo")
                        .HasColumnType("bytea")
                        .HasColumnName("IDENTITY_NO");

                    b.Property<bool?>("IdentityPermanent")
                        .HasColumnType("boolean")
                        .HasColumnName("IDENTITY_PERMANENT");

                    b.Property<string>("IdentityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("IDENTITY_TYPE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("LanguagePreferenceCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LANGUAGE_PREFERENCE_CODE");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("LastNameEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LAST_NAME_EN");

                    b.Property<string>("MaritalStatusCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("MARITAL_STATUS_CODE");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("MIDDLE_NAME");

                    b.Property<string>("MiddleNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("MIDDLE_NAME_EN");

                    b.Property<string>("NationalityCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NATIONALITY_CODE");

                    b.Property<string>("OrganizationBusinessType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ORGANIZATION_BUSINESS_TYPE");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ORGANIZATION_NAME");

                    b.Property<string>("OrganizationNameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ORGANIZATION_NAME_EN");

                    b.Property<DateTime?>("OrganizationRegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ORGANIZATION_REGISTRATION_DATE");

                    b.Property<string>("PlaceOfBirthCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PLACE_OF_BIRTH_CITY");

                    b.Property<string>("PlaceOfBirthCountryCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PLACE_OF_BIRTH_COUNTRY_CODE");

                    b.Property<decimal?>("PremiumCapacity")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("PREMIUM_CAPACITY");

                    b.Property<byte[]>("PrimaryIncomeLevelCode")
                        .HasColumnType("bytea")
                        .HasColumnName("PRIMARY_INCOME_LEVEL_CODE");

                    b.Property<byte[]>("PrimaryIncomePerYear")
                        .HasColumnType("bytea")
                        .HasColumnName("PRIMARY_INCOME_PER_YEAR");

                    b.Property<string>("PrimaryOccupationBusinessType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PRIMARY_OCCUPATION_BUSINESS_TYPE");

                    b.Property<byte[]>("PrimaryOccupationCode")
                        .HasColumnType("bytea")
                        .HasColumnName("PRIMARY_OCCUPATION_CODE");

                    b.Property<string>("PrimaryOccupationOrganizationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PRIMARY_OCCUPATION_ORGANIZATION_NAME");

                    b.Property<byte[]>("PrimaryOccupationPositionCode")
                        .HasColumnType("bytea")
                        .HasColumnName("PRIMARY_OCCUPATION_POSITION_CODE");

                    b.Property<string>("ReceivesEmailNews")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("RECEIVES_EMAIL_NEWS");

                    b.Property<string>("RefId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("REF_ID");

                    b.Property<byte[]>("ReligionCode")
                        .HasColumnType("bytea")
                        .HasColumnName("RELIGION_CODE");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("REMARK");

                    b.Property<byte[]>("SecondaryIncomeLevelCode")
                        .HasColumnType("bytea")
                        .HasColumnName("SECONDARY_INCOME_LEVEL_CODE");

                    b.Property<byte[]>("SecondaryIncomePerYear")
                        .HasColumnType("bytea")
                        .HasColumnName("SECONDARY_INCOME_PER_YEAR");

                    b.Property<string>("SecondaryOccupationBusinessType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SECONDARY_OCCUPATION_BUSINESS_TYPE");

                    b.Property<byte[]>("SecondaryOccupationCode")
                        .HasColumnType("bytea")
                        .HasColumnName("SECONDARY_OCCUPATION_CODE");

                    b.Property<string>("SecondaryOccupationOrganizationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SECONDARY_OCCUPATION_ORGANIZATION_NAME");

                    b.Property<byte[]>("SecondaryOccupationPositionCode")
                        .HasColumnType("bytea")
                        .HasColumnName("SECONDARY_OCCUPATION_POSITION_CODE");

                    b.Property<string>("SuffixName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SUFFIX_NAME");

                    b.Property<string>("SuffixNameEn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SUFFIX_NAME_EN");

                    b.Property<byte[]>("TaxId")
                        .HasColumnType("bytea")
                        .HasColumnName("TAX_ID");

                    b.Property<DateTime?>("TerminatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TERMINATED_DATE");

                    b.Property<bool?>("TerminatedFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("TERMINATED_FLAG");

                    b.Property<string>("TerminatedReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TERMINATED_REASON");

                    b.Property<string>("TitleCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TITLE_CODE");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode")
                        .IsUnique();

                    b.HasIndex("RefId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("t_client", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientCode = "CLI0001",
                            ClientTypeCode = "INDIVIDUAL",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "สมชาย",
                            FirstNameEn = "Somchai",
                            GenderCode = "M",
                            IdentityType = "NATIONAL_ID",
                            IsActive = true,
                            LanguagePreferenceCode = "TH",
                            LastName = "ใจดี",
                            LastNameEn = "Jaidee",
                            MaritalStatusCode = "MARRIED",
                            NationalityCode = "THA",
                            PremiumCapacity = 50000.00m,
                            PrimaryOccupationBusinessType = "TRADING",
                            PrimaryOccupationOrganizationName = "ABC Trading Co., Ltd.",
                            RefId = "AG0001",
                            TitleCode = "MR",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("1f8d0f1a-548d-442b-9bd9-e1232073f137")
                        },
                        new
                        {
                            Id = 2,
                            ClientCode = "CLI0002",
                            ClientTypeCode = "INDIVIDUAL",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DateOfBirth = new DateTime(1990, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "สมหญิง",
                            FirstNameEn = "Somying",
                            GenderCode = "F",
                            IdentityType = "NATIONAL_ID",
                            IsActive = true,
                            LanguagePreferenceCode = "TH",
                            LastName = "รักดี",
                            LastNameEn = "Rakdee",
                            MaritalStatusCode = "SINGLE",
                            NationalityCode = "THA",
                            PremiumCapacity = 75000.00m,
                            PrimaryOccupationBusinessType = "GOVERNMENT",
                            PrimaryOccupationOrganizationName = "Ministry of Finance",
                            RefId = "AG0001",
                            TitleCode = "MRS",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("150d0663-1f23-45d3-99ac-5971a9cefcb3")
                        },
                        new
                        {
                            Id = 3,
                            ClientCode = "CLI0003",
                            ClientTypeCode = "ORGANIZATION",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            IdentityType = "TAX_ID",
                            IsActive = true,
                            LanguagePreferenceCode = "TH",
                            NationalityCode = "THA",
                            OrganizationBusinessType = "INSURANCE",
                            OrganizationName = "บริษัท ไทยประกันภัย จำกัด",
                            OrganizationNameEn = "Thai Insurance Company Limited",
                            OrganizationRegistrationDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PremiumCapacity = 5000000.00m,
                            RefId = "AE0001",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("bd080399-3157-4c3f-9dc5-069e2ea237bb")
                        },
                        new
                        {
                            Id = 4,
                            ClientCode = "CLI0004",
                            ClientTypeCode = "INDIVIDUAL",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DateOfBirth = new DateTime(1975, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "John",
                            FirstNameEn = "John",
                            GenderCode = "M",
                            IdentityType = "PASSPORT",
                            IsActive = true,
                            LanguagePreferenceCode = "EN",
                            LastName = "Smith",
                            LastNameEn = "Smith",
                            MaritalStatusCode = "MARRIED",
                            NationalityCode = "USA",
                            PlaceOfBirthCity = "New York",
                            PlaceOfBirthCountryCode = "USA",
                            PremiumCapacity = 200000.00m,
                            PrimaryOccupationBusinessType = "TECHNOLOGY",
                            PrimaryOccupationOrganizationName = "Tech Global Inc.",
                            RefId = "AE0001",
                            TitleCode = "MR",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("5402c760-253a-475f-a537-59d0d67ee232")
                        });
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressAlley")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_ALLEY");

                    b.Property<string>("AddressDetail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ADDRESS_DETAIL");

                    b.Property<string>("AddressMoo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ADDRESS_MOO");

                    b.Property<string>("AddressNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ADDRESS_NO");

                    b.Property<string>("AddressRoad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_ROAD");

                    b.Property<string>("AddressTypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ADDRESS_TYPE_CODE");

                    b.Property<string>("AddressVillageBuilding")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_VILLAGE_BUILDING");

                    b.Property<string>("AddressWorkplaceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_WORKPLACE_NAME");

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLIENT_CODE");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("COUNTRY_CODE");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("DistrictCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DISTRICT_CODE");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_PRIMARY");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("POSTAL_CODE");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PROVINCE_CODE");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("REMARK");

                    b.Property<string>("SubdistrictCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SUBDISTRICT_CODE");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("t_client_address", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressDetail = "ซอยลาดพร้าว 101",
                            AddressMoo = "5",
                            AddressNo = "123/45",
                            AddressRoad = "ลาดพร้าว",
                            AddressTypeCode = "HOME",
                            ClientCode = "CLI0001",
                            CountryCode = "THA",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DistrictCode = "1001",
                            IsPrimary = true,
                            PostalCode = "10230",
                            ProvinceCode = "10",
                            SubdistrictCode = "100101",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("1a7fad59-c8c1-4784-8e9e-3b88e9116a4d")
                        },
                        new
                        {
                            Id = 2,
                            AddressNo = "567/89",
                            AddressRoad = "พระราม 9",
                            AddressTypeCode = "HOME",
                            AddressVillageBuilding = "หมู่บ้านสุขใจ",
                            ClientCode = "CLI0002",
                            CountryCode = "THA",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DistrictCode = "1001",
                            IsPrimary = true,
                            PostalCode = "10250",
                            ProvinceCode = "10",
                            SubdistrictCode = "100102",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("0d10ceed-1904-4f72-8063-b8de35987662")
                        },
                        new
                        {
                            Id = 3,
                            AddressNo = "999",
                            AddressRoad = "สาทร",
                            AddressTypeCode = "OFFICE",
                            AddressVillageBuilding = "อาคารไทยประกัน ทาวเวอร์",
                            ClientCode = "CLI0003",
                            CountryCode = "THA",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DistrictCode = "1002",
                            IsPrimary = true,
                            PostalCode = "10120",
                            ProvinceCode = "10",
                            SubdistrictCode = "100201",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("65b6d912-10cf-4061-989b-539a79be9b02")
                        },
                        new
                        {
                            Id = 4,
                            AddressNo = "88/12",
                            AddressRoad = "Sukhumvit",
                            AddressTypeCode = "HOME",
                            AddressVillageBuilding = "Luxury Condo",
                            ClientCode = "CLI0004",
                            CountryCode = "THA",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DistrictCode = "1003",
                            IsPrimary = true,
                            PostalCode = "10110",
                            ProvinceCode = "10",
                            SubdistrictCode = "100301",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("979e71b5-e2c5-44d8-bdef-7ddf0f79e1d6")
                        });
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLIENT_CODE");

                    b.Property<string>("ContactTypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CONTACT_TYPE_CODE");

                    b.Property<string>("ContactValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("CONTACT_VALUE");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_DATE");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_PRIMARY");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("REMARK");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("t_client_contact", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientCode = "CLI0001",
                            ContactTypeCode = "MOBILE",
                            ContactValue = "081-234-5678",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            IsPrimary = true,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("6d5909ae-010e-4016-bee9-2ca04907605d")
                        },
                        new
                        {
                            Id = 2,
                            ClientCode = "CLI0001",
                            ContactTypeCode = "EMAIL",
                            ContactValue = "somchai.j@email.com",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            IsPrimary = false,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("e7f9f4bd-b7a6-445b-9146-ce4c62e091a7")
                        },
                        new
                        {
                            Id = 3,
                            ClientCode = "CLI0002",
                            ContactTypeCode = "MOBILE",
                            ContactValue = "082-345-6789",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            IsPrimary = true,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("1820f6e9-c76d-4380-9621-a45fe5ef6dfe")
                        },
                        new
                        {
                            Id = 4,
                            ClientCode = "CLI0002",
                            ContactTypeCode = "EMAIL",
                            ContactValue = "somying.r@email.com",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            IsPrimary = false,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("4e418ee5-04dd-47fc-8372-fbffb5ae48d4")
                        },
                        new
                        {
                            Id = 5,
                            ClientCode = "CLI0003",
                            ContactTypeCode = "OFFICE_PHONE",
                            ContactValue = "02-123-4567",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            IsPrimary = true,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("29f9268d-b012-4b39-9473-46b5cea7e0f1")
                        },
                        new
                        {
                            Id = 6,
                            ClientCode = "CLI0003",
                            ContactTypeCode = "EMAIL",
                            ContactValue = "info@thaiinsurance.com",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            IsPrimary = false,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("45e53000-0efc-44e9-9a26-0233c92d1639")
                        },
                        new
                        {
                            Id = 7,
                            ClientCode = "CLI0004",
                            ContactTypeCode = "MOBILE",
                            ContactValue = "+1-555-1234",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            IsPrimary = true,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("f303958f-6ece-4ee2-8897-6fc34cf7edce")
                        },
                        new
                        {
                            Id = 8,
                            ClientCode = "CLI0004",
                            ContactTypeCode = "EMAIL",
                            ContactValue = "john.smith@techglobal.com",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            IsPrimary = false,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("60db4a13-6513-4b13-b8e0-93fd728bd5bb")
                        });
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CLIENT_CODE");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_DATE");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EFFECTIVE_DATE");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EXPIRY_DATE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("PolicyNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("POLICY_NO");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("REFERENCE_NO");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("REMARK");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROLE_CODE");

                    b.Property<int?>("RoleSeqNo")
                        .HasColumnType("integer")
                        .HasColumnName("ROLE_SEQ_NO");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("UUID");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("t_client_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientCode = "CLI0001",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyNo = "POL001-2025",
                            ReferenceNo = "POL-2025-001",
                            Remark = "Life Insurance Policy Owner",
                            RoleCode = "POLICY_OWNER",
                            RoleSeqNo = 1,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("66c11b5f-b802-4afe-a412-d8e33ebeade1")
                        },
                        new
                        {
                            Id = 2,
                            ClientCode = "CLI0001",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyNo = "POL001-2025",
                            ReferenceNo = "POL-2025-001",
                            Remark = "Insured Person",
                            RoleCode = "INSURED",
                            RoleSeqNo = 1,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("a3d185b7-4b18-471b-a055-58b6ba0cb497")
                        },
                        new
                        {
                            Id = 3,
                            ClientCode = "CLI0002",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyNo = "POL001-2025",
                            ReferenceNo = "POL-2025-001",
                            Remark = "Primary Beneficiary - Spouse",
                            RoleCode = "BENEFICIARY",
                            RoleSeqNo = 1,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("5acef5af-a3e2-40b9-9c0b-1b4092df7083")
                        },
                        new
                        {
                            Id = 4,
                            ClientCode = "CLI0003",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyNo = "CORP001-2025",
                            ReferenceNo = "CORP-2025-001",
                            Remark = "Corporate Insurance Client",
                            RoleCode = "CORPORATE_CLIENT",
                            RoleSeqNo = 1,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("5698af4b-a98b-4e79-93e5-dcac5c607457")
                        },
                        new
                        {
                            Id = 5,
                            ClientCode = "CLI0004",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            EffectiveDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PolicyNo = "POL002-2025",
                            ReferenceNo = "POL-2025-002",
                            Remark = "Expatriate Policy Owner",
                            RoleCode = "POLICY_OWNER",
                            RoleSeqNo = 1,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("2a75e855-f8d0-4bb6-9098-1160b1677bab")
                        });
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Hierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HierarchyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("HierarchyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyCode")
                        .IsUnique();

                    b.HasIndex("RankId");

                    b.ToTable("hierarchies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HierarchyCode = "A1",
                            HierarchyName = "Hierarchy A1",
                            Level = 1,
                            RankId = 1
                        },
                        new
                        {
                            Id = 2,
                            HierarchyCode = "A2",
                            HierarchyName = "Hierarchy A2",
                            Level = 2,
                            RankId = 1
                        },
                        new
                        {
                            Id = 3,
                            HierarchyCode = "A3",
                            HierarchyName = "Hierarchy A3",
                            Level = 3,
                            RankId = 1
                        },
                        new
                        {
                            Id = 4,
                            HierarchyCode = "A4",
                            HierarchyName = "Hierarchy A4",
                            Level = 4,
                            RankId = 2
                        },
                        new
                        {
                            Id = 5,
                            HierarchyCode = "A5",
                            HierarchyName = "Hierarchy A5",
                            Level = 5,
                            RankId = 2
                        },
                        new
                        {
                            Id = 6,
                            HierarchyCode = "A6",
                            HierarchyName = "Hierarchy A6",
                            Level = 6,
                            RankId = 2
                        },
                        new
                        {
                            Id = 7,
                            HierarchyCode = "A7",
                            HierarchyName = "Hierarchy A7",
                            Level = 7,
                            RankId = 3
                        },
                        new
                        {
                            Id = 8,
                            HierarchyCode = "A8",
                            HierarchyName = "Hierarchy A8",
                            Level = 8,
                            RankId = 3
                        },
                        new
                        {
                            Id = 9,
                            HierarchyCode = "A9",
                            HierarchyName = "Hierarchy A9",
                            Level = 9,
                            RankId = 3
                        });
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CONTENT_TYPE");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("DISPLAY_ORDER");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("FILE_NAME");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FILE_PATH");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("FILE_SIZE");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FILE_URL");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("HEIGHT");

                    b.Property<string>("ImageCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("IMAGE_CATEGORY");

                    b.Property<string>("ImageCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("IMAGE_CODE");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea")
                        .HasColumnName("IMAGE_DATA");

                    b.Property<string>("ImageTypeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("IMAGE_TYPE_CODE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_PRIMARY");

                    b.Property<string>("RefId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("REF_ID");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("REMARK");

                    b.Property<byte[]>("ThumbnailData")
                        .HasColumnType("bytea")
                        .HasColumnName("THUMBNAIL_DATA");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("THUMBNAIL_URL");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("UUID");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("WIDTH");

                    b.HasKey("Id");

                    b.HasIndex("ImageCode")
                        .IsUnique();

                    b.HasIndex("RefId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("t_image", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentType = "image/jpeg",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DisplayOrder = 1,
                            FileName = "somchai_profile.jpg",
                            FileSize = 70L,
                            Height = 600,
                            ImageCategory = "PERSONAL",
                            ImageCode = "IMG0001",
                            ImageData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 252, 255, 159, 161, 30, 0, 7, 130, 2, 127, 61, 200, 72, 239, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            ImageTypeCode = "PROFILE",
                            IsActive = true,
                            IsPrimary = true,
                            RefId = "CLI0001",
                            Remark = "Profile picture",
                            ThumbnailData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 100, 248, 207, 80, 15, 0, 3, 134, 1, 128, 90, 52, 125, 107, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("11111111-1111-1111-1111-111111111111"),
                            Width = 800
                        },
                        new
                        {
                            Id = 2,
                            ContentType = "image/jpeg",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DisplayOrder = 2,
                            FileName = "somchai_idcard.jpg",
                            FileSize = 70L,
                            Height = 768,
                            ImageCategory = "DOCUMENT",
                            ImageCode = "IMG0002",
                            ImageData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 252, 255, 159, 161, 30, 0, 7, 130, 2, 127, 61, 200, 72, 239, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            ImageTypeCode = "ID_CARD",
                            IsActive = true,
                            IsPrimary = false,
                            RefId = "CLI0001",
                            Remark = "National ID Card",
                            ThumbnailData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 100, 248, 207, 80, 15, 0, 3, 134, 1, 128, 90, 52, 125, 107, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("22222222-2222-2222-2222-222222222222"),
                            Width = 1024
                        },
                        new
                        {
                            Id = 3,
                            ContentType = "image/jpeg",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DisplayOrder = 1,
                            FileName = "somying_profile.jpg",
                            FileSize = 70L,
                            Height = 600,
                            ImageCategory = "PERSONAL",
                            ImageCode = "IMG0003",
                            ImageData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 252, 255, 159, 161, 30, 0, 7, 130, 2, 127, 61, 200, 72, 239, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            ImageTypeCode = "PROFILE",
                            IsActive = true,
                            IsPrimary = true,
                            RefId = "CLI0002",
                            Remark = "Profile picture",
                            ThumbnailData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 100, 248, 207, 80, 15, 0, 3, 134, 1, 128, 90, 52, 125, 107, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("33333333-3333-3333-3333-333333333333"),
                            Width = 800
                        },
                        new
                        {
                            Id = 4,
                            ContentType = "image/png",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DisplayOrder = 1,
                            FileName = "thai_insurance_logo.png",
                            FileSize = 70L,
                            Height = 400,
                            ImageCategory = "CORPORATE",
                            ImageCode = "IMG0004",
                            ImageData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 252, 255, 159, 161, 30, 0, 7, 130, 2, 127, 61, 200, 72, 239, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            ImageTypeCode = "COMPANY_LOGO",
                            IsActive = true,
                            IsPrimary = true,
                            RefId = "CLI0003",
                            Remark = "Company Logo",
                            ThumbnailData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 100, 248, 207, 80, 15, 0, 3, 134, 1, 128, 90, 52, 125, 107, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("44444444-4444-4444-4444-444444444444"),
                            Width = 400
                        },
                        new
                        {
                            Id = 5,
                            ContentType = "image/jpeg",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DisplayOrder = 2,
                            FileName = "company_registration.pdf.jpg",
                            FileSize = 70L,
                            Height = 1600,
                            ImageCategory = "DOCUMENT",
                            ImageCode = "IMG0005",
                            ImageData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 252, 255, 159, 161, 30, 0, 7, 130, 2, 127, 61, 200, 72, 239, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            ImageTypeCode = "REGISTRATION",
                            IsActive = true,
                            IsPrimary = false,
                            RefId = "CLI0003",
                            Remark = "Company Registration Document",
                            ThumbnailData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 100, 248, 207, 80, 15, 0, 3, 134, 1, 128, 90, 52, 125, 107, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("55555555-5555-5555-5555-555555555555"),
                            Width = 1200
                        },
                        new
                        {
                            Id = 6,
                            ContentType = "image/jpeg",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DisplayOrder = 1,
                            FileName = "john_passport.jpg",
                            FileSize = 70L,
                            Height = 768,
                            ImageCategory = "DOCUMENT",
                            ImageCode = "IMG0006",
                            ImageData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 252, 255, 159, 161, 30, 0, 7, 130, 2, 127, 61, 200, 72, 239, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            ImageTypeCode = "PASSPORT",
                            IsActive = true,
                            IsPrimary = true,
                            RefId = "CLI0004",
                            Remark = "Passport Photo Page",
                            ThumbnailData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 100, 248, 207, 80, 15, 0, 3, 134, 1, 128, 90, 52, 125, 107, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("66666666-6666-6666-6666-666666666666"),
                            Width = 1024
                        },
                        new
                        {
                            Id = 7,
                            ContentType = "image/png",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            DisplayOrder = 2,
                            FileName = "john_signature.png",
                            FileSize = 70L,
                            Height = 200,
                            ImageCategory = "VERIFICATION",
                            ImageCode = "IMG0007",
                            ImageData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 252, 255, 159, 161, 30, 0, 7, 130, 2, 127, 61, 200, 72, 239, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            ImageTypeCode = "SIGNATURE",
                            IsActive = true,
                            IsPrimary = false,
                            RefId = "CLI0004",
                            Remark = "Digital Signature",
                            ThumbnailData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 13, 73, 68, 65, 84, 120, 218, 99, 100, 248, 207, 80, 15, 0, 3, 134, 1, 128, 90, 52, 125, 107, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2025, 11, 13, 9, 10, 37, 45, DateTimeKind.Utc).AddTicks(7176),
                            Uuid = new Guid("77777777-7777-7777-7777-777777777777"),
                            Width = 400
                        });
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("licenses", (string)null);
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("RankCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RankCode")
                        .IsUnique();

                    b.ToTable("ranks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 1,
                            RankCode = "AG",
                            RankName = "Agent General"
                        },
                        new
                        {
                            Id = 2,
                            Level = 2,
                            RankCode = "AL",
                            RankName = "Agent Leader"
                        },
                        new
                        {
                            Id = 3,
                            Level = 3,
                            RankCode = "AE",
                            RankName = "Agent Executive"
                        });
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Agent", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Hierarchy", "Hierarchy")
                        .WithMany("Agents")
                        .HasForeignKey("HierarchyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgentHierarchyApi.Models.Agent", "ParentAgent")
                        .WithMany("ChildAgents")
                        .HasForeignKey("ParentAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgentHierarchyApi.Models.Rank", "Rank")
                        .WithMany("Agents")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hierarchy");

                    b.Navigation("ParentAgent");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Client", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Agent", "ReferenceAgent")
                        .WithMany()
                        .HasForeignKey("RefId")
                        .HasPrincipalKey("AgentCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReferenceAgent");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientAddress", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Client", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientCode")
                        .HasPrincipalKey("ClientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientContact", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Client", "Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientCode")
                        .HasPrincipalKey("ClientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.ClientRole", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Client", "Client")
                        .WithMany("Roles")
                        .HasForeignKey("ClientCode")
                        .HasPrincipalKey("ClientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Hierarchy", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Rank", "Rank")
                        .WithMany("Hierarchies")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Image", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Client", "ReferenceClient")
                        .WithMany("Images")
                        .HasForeignKey("RefId")
                        .HasPrincipalKey("ClientCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReferenceClient");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.License", b =>
                {
                    b.HasOne("AgentHierarchyApi.Models.Agent", "Agent")
                        .WithMany("Licenses")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Agent", b =>
                {
                    b.Navigation("ChildAgents");

                    b.Navigation("Licenses");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");

                    b.Navigation("Images");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Hierarchy", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("AgentHierarchyApi.Models.Rank", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Hierarchies");
                });
#pragma warning restore 612, 618
        }
    }
}
